### ISSUE TITLE
State management and synchronisation library 

### ISSUE THREAD

**Issue by Dassderdie** [hpi-sam/digital-fuesim-manv#1]
### Synchronisation between server/clients
* a client can subscribe to a part of the state (example: all vehicles and personnel in `viewport1` (= calculated via coordinates))
* state should be robustly stored (backups) and handled (= database)
* the state change can be executed without conflicts (e.g. a client changing the position of a vehicle during the state-update)
* state changes should be validated by a trusted entity
* a client gets updates to the state in real-time (e.g. "push" like websockets, no polling)

### (local) State management client
* in the client one should be able to subscribe to a part of the state (async observer pattern) and get snapshotted values directly  in a synchronous way
* nicely encapsulated client-side [optimistic updates](https://stackoverflow.com/a/33009713/12698757) for more responsive ux

### both
* a client can modify the data and send the change to the server/the other clients
* very good typings and reusability across all codebases (client and server)

## TODOs
* [x] API design websockets
* [x] senden des States über websocket verbindung
* [x] backend ordentlich machen (file structure, watch mode)
* [x] action validation (@ClFeSc)
* [ ] setup test frameworks
    * [x] backend
    * [ ] shared
    * [ ] frontend unit tests
    * [ ] e2e
* [x] optimistic updates
* [ ] Add actionNr to `performAction` and `getState` to fix possible synchronisation issues
* [ ] Resolve all TODOs in the current code base

### realtime database
* [firebase realtime database](https://firebase.google.com/docs/database)
* [SapphireDb](https://sapphire-db.com/start/main)
* [supabase](https://supabase.io/)
* [roomservice](https://www.roomservice.dev/)
* [replicache](https://replicache.dev/)

### client-side state management (stores)
* [NGXS](https://www.ngxs.io/)
* [NGRX](https://ngrx.io/)
