### ISSUE TITLE
Create a release process

### ISSUE THREAD

**Issue by Dassderdie** [hpi-sam/digital-fuesim-manv#587]
* [ ] Decide on a workflow and versioning (Maybe a changelog would be nice too?)
* [ ] Document this workflow and the versioning in the repository (e.g. root README)
* [ ] Maybe create/use a pipeline/script/bot to streamline this process

See #584

**Comment by ClFeSc** [comment]
> * [ ]  Decide on a workflow and versioning (Maybe a changelog would be nice too?)

At least the changelog from GitHub should be used.

**Comment by ClFeSc** [comment]
> * [ ]  Document this workflow and the versioning in the repository (e.g. root README)

This should include all the places where a version number needs to be bumped.

**Comment by lukasrad02** [comment]
As stated in #585, we will merge into the `main` branch after each milestone. For each of this merges, we will create a release on GitHub, too.

We still have to decide on the details like versioning and will document the complete release process afterwards.
